//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rubbish {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rubbish.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 啊阿吖
        ///埃挨哎唉哀皑癌蔼矮艾碍爱隘捱嗳嗌嫒瑷暧砹锿霭
        ///鞍氨安俺按暗岸胺案谙埯揞庵桉铵鹌黯
        ///肮昂盎
        ///凹敖熬翱袄傲奥懊澳坳拗遨獒螯鏊鳌
        ///芭捌扒叭吧笆八疤巴拔跋靶把耙坝霸罢爸茇菝岜灞钯粑鲅魃
        ///白柏百摆佰败拜稗捭呗掰
        ///斑班搬扳般颁板版扮拌伴瓣半办绊阪坂钣瘢癍舨
        ///邦帮梆榜膀绑棒磅蚌镑傍谤蒡浜
        ///苞胞包褒剥薄雹保堡饱宝抱报暴豹鲍爆葆孢煲褓趵龅
        ///杯碑悲卑北辈背贝钡倍狈备惫焙被孛陂邶蓓悖碚
        ///奔苯本笨锛
        ///崩绷甭泵蹦迸嘣
        ///逼鼻比鄙笔彼碧蓖蔽毕毙毖币庇痹闭敝弊必辟壁臂避陛匕
        ///鞭边编贬扁便变卞辨辩辫遍匾弁忭汴缏煸砭碥窆褊蝙笾鳊
        ///标彪膘表婊骠杓飑飙飚镖镳裱鳔
        ///鳖憋别瘪蹩
        ///彬斌濒滨宾摈傧缤玢槟殡膑镔髌鬓
        ///兵冰柄丙秉饼炳病并禀摒
        ///玻菠播拨钵波博勃搏铂箔伯帛舶脖膊渤泊驳啵饽礴钹鹁簸跛
        ///捕卜哺补埠不布步簿部怖卟逋晡钚钸
        ///擦嚓
        ///猜裁材才财睬踩采彩菜蔡
        ///餐参蚕残惭惨灿骖璨粲
        ///苍舱仓沧藏
        ///操糙槽曹草嘈漕艚
        ///厕策侧册测恻
        ///岑涔
        ///层蹭噌
        ///插叉茬茶查碴搽察岔差诧猹馇汊杈楂槎檫锸镲衩
        ///拆柴豺钗
        ///搀掺蝉馋谗缠铲产阐颤谄忏潺羼婵
        ///昌猖场尝常长偿肠厂敞畅唱倡伥苌菖徜怅惝阊娼嫦
        ///超抄钞朝嘲潮巢吵炒焯耖 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string replacedic {
            get {
                return ResourceManager.GetString("replacedic", resourceCulture);
            }
        }
    }
}
